---
- name: Create required directories
  loop: "{{ checkmk_default_folders + checkmk_extra_folders }}"
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    state: directory
  tags:
    - checkmk

- name: Write default config
  notify:
    - Restart checkmk
  ansible.builtin.template:
    src: default.j2
    dest: /etc/default/checkmk
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - checkmk

- name: Write service file
  notify:
    - Restart checkmk
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/checkmk.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - checkmk

- name: Pull docker image
  when:
    - checkmk_pull_image
  community.docker.docker_image:
    name: "{{ checkmk_image }}"
    source: pull
  tags:
    - checkmk

- name: Create docker network
  when:
    - false if checkmk_network is none else (checkmk_network | length > 0)
  community.docker.docker_network:
    name: '{{ checkmk_network }}'
  tags:
    - checkmk

- name: Start checkmk service
  ansible.builtin.systemd:
    name: checkmk
    state: started
    daemon_reload: true
    masked: false
    enabled: true
  tags:
    - checkmk

...
